[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/ocr"
  to = "/.netlify/functions/ocr"
  status = 200

[[redirects]]
  from = "/api/db"
  to = "/.netlify/functions/db"
  status = 200
